parse_config:
  raw_binding_map:
    "&caps_word": "CAPS WORD"
    "&emoji_m": "EMOJI"
    "&spotl_m": "SPTL"
    "&c_back_m": "CURS BACK"
    "&c_forward_m": "CURS FORW"
    "&btclr_m": "BTCLR"
    "&outtog_m": "OUT TOG"
    "&btsel_m 0": "BT0"
    "&btsel_m 1": "BT1"
    "&btsel_m 2": "BT2"
    "&soft_off_m": "SLEEP"
    "&kp LEFT": "\u2190"
    "&kp UP": "\u2191"
    "&kp RIGHT": "\u2192"
    "&kp DOWN": "\u2193"
    "&kp LALT": "ALT"
    "&kp RALT": "ALT"
    "&kp LGUI": "GUI"
    "&kp LCTRL": "CTRL"
    "&kp RCTRL": "CTRL"
    "&kp LSHIFT": "SHIFT"
    "&kp RSHIFT": "SHIFT"
    "&noop_m": ""
    "&none": ""

draw_config:
  dark_mode: true
  svg_extra_style: |
    text.label, text.footer {
      stroke: none;
      fill: #FFF;
      font-weight: 500; 
      paint-order: normal;
    }
