parse_config:
  raw_binding_map:
    "&emoji_m": "EMOJI"
    "&spotl_m": "SPTL"
    "&c_back_m": "CBACK"
    "&c_forward_m": "CFORWARD"
    "&btclr_m": "BTCLR"
    "&outtog_m": "TOGOUT"
    "&btsel_m 0": "BT0"
    "&btsel_m 1": "BT1"
    "&btsel_m 2": "BT2"
    "&kp LEFT": "\u2190"
    "&kp UP": "\u2191"
    "&kp RIGHT": "\u2192"
    "&kp DOWN": "\u2193"
    "&kp LALT": "ALT"
    "&kp RALT": "ALT"
    "&noop_m": ""
    "&none": ""
